# Generated by Django 2.2.5 on 2021-11-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=10, unique=True)),
                ('pub_data', models.DateField(max_length=20)),
                ('describle', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
