# Generated by Django 2.2.5 on 2021-11-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksinfo',
            options={'verbose_name': '用户管理'},
        ),
        migrations.AlterModelTable(
            name='booksinfo',
            table='bookinfo',
        ),
    ]
